usertitle: nEDM Top
repohash:
  System-Overview:
    description: |
      (Read this first!) Set of pages describing the general functionality of
      many of the (non-software) systems used in the nEDM experiment.
    name: System Overview
  nEDM-Interface:
    name: nEDM Interface
    description: |
      Page describing the web interface used for control of devices and
      visualization of data in the experiment.
  Python-Slow-Control:
    name: pynedm
  HimbeereCouch:
    name: himbeerecouch
  FileServer-Docker:
    name: File Server (Docker)
  Munin-Docker:
    name: Munin (Docker)
  CouchDB-Docker:
    name: CouchDB (Docker)
  VMEDAQBox:
    name: VMEDAQBox
    description: |
      Library for using HardwareLib software via JSON objects, allowing web
      interfaces.
  Slow-Control-Misc:
    name: Miscellaneous Slow Control software

